var namespacemdbx =
[
    [ "allocation_aware_details", "namespacemdbx_1_1allocation__aware__details.html", "namespacemdbx_1_1allocation__aware__details" ],
    [ "buffer", "classmdbx_1_1buffer.html", "classmdbx_1_1buffer" ],
    [ "cursor", "classmdbx_1_1cursor.html", "classmdbx_1_1cursor" ],
    [ "cursor_managed", "classmdbx_1_1cursor__managed.html", "classmdbx_1_1cursor__managed" ],
    [ "default_capacity_policy", "structmdbx_1_1default__capacity__policy.html", "structmdbx_1_1default__capacity__policy" ],
    [ "env", "classmdbx_1_1env.html", "classmdbx_1_1env" ],
    [ "env_managed", "classmdbx_1_1env__managed.html", "classmdbx_1_1env__managed" ],
    [ "error", "classmdbx_1_1error.html", "classmdbx_1_1error" ],
    [ "exception", "classmdbx_1_1exception.html", "classmdbx_1_1exception" ],
    [ "exception_thunk", "classmdbx_1_1exception__thunk.html", "classmdbx_1_1exception__thunk" ],
    [ "fatal", "classmdbx_1_1fatal.html", "classmdbx_1_1fatal" ],
    [ "from_base58", "structmdbx_1_1from__base58.html", "structmdbx_1_1from__base58" ],
    [ "from_base64", "structmdbx_1_1from__base64.html", "structmdbx_1_1from__base64" ],
    [ "from_hex", "structmdbx_1_1from__hex.html", "structmdbx_1_1from__hex" ],
    [ "map_handle", "structmdbx_1_1map__handle.html", "structmdbx_1_1map__handle" ],
    [ "pair", "structmdbx_1_1pair.html", "structmdbx_1_1pair" ],
    [ "pair_result", "structmdbx_1_1pair__result.html", "structmdbx_1_1pair__result" ],
    [ "slice", "structmdbx_1_1slice.html", "structmdbx_1_1slice" ],
    [ "to_base58", "structmdbx_1_1to__base58.html", "structmdbx_1_1to__base58" ],
    [ "to_base64", "structmdbx_1_1to__base64.html", "structmdbx_1_1to__base64" ],
    [ "to_hex", "structmdbx_1_1to__hex.html", "structmdbx_1_1to__hex" ],
    [ "txn", "classmdbx_1_1txn.html", "classmdbx_1_1txn" ],
    [ "txn_managed", "classmdbx_1_1txn__managed.html", "classmdbx_1_1txn__managed" ],
    [ "value_result", "structmdbx_1_1value__result.html", "structmdbx_1_1value__result" ]
];